### ISSUE TITLE
Add NathanWalker to formly-js org

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng-formly-nativescript#1]
@kentcdodds please add @NathanWalker to @formly-js/angular2-formly-core-team

**Comment by kentcdodds** [comment]
What do I need to do to give you permission to do this kind of stuff yourself. I'd prefer to not have to keep doing this...

**Comment by mohammedzamakhan** [comment]
I have no idea who all has that access in a github organization. I would love to have that access, but currently I don't have it

**Comment by mohammedzamakhan** [comment]
Probably you will have to make me an admin for the organization

**Comment by kentcdodds** [comment]
Alrighty, you are now an owner of the org. Thanks!
