### ISSUE TITLE
How do I run this demo example?

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng-formly-nativescript#3]
@NathanWalker I got nativescript up and running on my machine. Let me know how to run the demo on my machine 😄

**Comment by mohammedzamakhan** [comment]
when I run `npm run demo.ios`

I get bunch of `tsc` errors

```
error TS2318: Cannot find global type 'Array'.

error TS2318: Cannot find global type 'Boolean'.

error TS2318: Cannot find global type 'Function'.

error TS2318: Cannot find global type 'IArguments'.

error TS2318: Cannot find global type 'Number'.

error TS2318: Cannot find global type 'Object'.

error TS2318: Cannot find global type 'RegExp'.

error TS2318: Cannot find global type 'String'.
```

**Comment by NathanWalker** [comment]
Ah yes appears one references file did not make it to repo. I'll commit that when I get back and let ya know.

**Comment by NathanWalker** [comment]
@mohammedzamakhan https://github.com/formly-js/ng-formly-nativescript/pull/4 should fix it for you and I added a readme with the gif and instructions to run.

**Comment by mohammedzamakhan** [comment]
Still not able to run, I see that it created the app on the ios emulator, but when I try to open it, I see the splash screen and then it closes automatically

**Comment by NathanWalker** [comment]
What's the stacktrace?
Also if you could zip up your clone and just post a link to download, I can doublecheck that you have everything.

**Comment by mohammedzamakhan** [comment]
```
file:///app/main.ts:1:0: JS ERROR SyntaxError: Importing binding name 'categories' is not found.
```

**Comment by mohammedzamakhan** [comment]
![kapture 2016-12-08 at 11 26 00](https://cloud.githubusercontent.com/assets/2327532/21020213/2419e9b8-bd39-11e6-9d6e-2f83965e207e.gif)

**Comment by mohammedzamakhan** [comment]
@NathanWalker fyi Nativescript readme.md file will also be shown on the ng-formly website

https://ng2.angular-formly.com/guides/nativescript-support.html

and if you want to make changes please feel free
https://github.com/formly-js/ng2.angular-formly.com

**Comment by NathanWalker** [comment]
Thanks @mohammedzamakhan did you change your project after cloning in anyway?
If so, please drop a download link to a zip of what you got.
Def not seeing that error here.

**Comment by mohammedzamakhan** [comment]
Its 619MB 😲  after compression 240MB

**Comment by mohammedzamakhan** [comment]
https://www.dropbox.com/s/dtmb04u18yyb5n0/ng-formly-nativescript.zip?dl=0

**Comment by NathanWalker** [comment]
Don't include node_modules, platforms, lib, or hooks ;) ... You can delete that zip and just rezip without those. 👍

**Comment by mohammedzamakhan** [comment]
[ng-formly-nativescript.zip](https://github.com/formly-js/ng-formly-nativescript/files/640569/ng-formly-nativescript.zip)

**Comment by NathanWalker** [comment]
Thanks! I'll check this out tonight and let ya know.

**Comment by mohammedzamakhan** [comment]
got this now

```
Command failed: ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/zamamoha/Desktop/v2/ng-formly-nativescript/src/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/zamamoha/Desktop/v2/ng-formly-nativescript/src/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/zamamoha/Desktop/v2/ng-formly-nativescript/src/platforms/ios/plugins-debug.xcconfig'))"
/Users/zamamoha/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Users/zamamoha/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by NathanWalker** [comment]
@mohammedzamakhan that's a new one! lol. Hmm what node/npm you on?
I'm using:
node 6.9.1
npm 3.10.9

**Comment by NathanWalker** [comment]
Also what version of XCode do you have installed?
I have 8.1.

**Comment by NathanWalker** [comment]
You may also want to try doing this:
```
sudo gem uninstall xcodeproj && sudo gem install xcodeproj
sudo gem uninstall cocoapods && sudo gem install cocoapods
```

**Comment by mohammedzamakhan** [comment]
Great 👍  It runs now 😄
